version: '3'

services:
  app:
    build: .
    container_name: app
    image: app
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: "postgres:15.1-alpine"
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proven

  integration:
    build:
      context: .
      dockerfile: integrationTests/Dockerfile
    container_name: integration
    image: integration
    depends_on:
      - app

volumes:
  pg-data:
